language: python

compiler:
  - gcc

sudo: false #true

# 2.6 does not work at the moment, so it is commented out.
python:
  #- "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-5
      - binutils
      - cmake
      - graphviz

#before_install:
#  #- sudo ln -fs /usr/bin/gfortran-5 /usr/bin/gfortran && gfortran --version
#  #- export PATH=".:$PATH"
#  - gcc -v
#  - gfortran -v

# command to install dependencies
install: "pip install -r requirements.travis.txt"

before_script:
    - ln -s /usr/bin/gfortran-5 /opt/gfortran
    - gfortran --version

# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - nosetests -v -w ./autotest
